/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as RescueRouteImport } from './routes/rescue'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as AuthorityRouteImport } from './routes/authority'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VolunteerIndexRouteImport } from './routes/volunteer.index'
import { Route as RescueIndexRouteImport } from './routes/rescue.index'
import { Route as CitizenIndexRouteImport } from './routes/citizen.index'
import { Route as AuthorityIndexRouteImport } from './routes/authority.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VolunteerTrainingRouteImport } from './routes/volunteer.training'
import { Route as VolunteerResourcesRouteImport } from './routes/volunteer.resources'
import { Route as VolunteerProfileRouteImport } from './routes/volunteer.profile'
import { Route as VolunteerOperationsRouteImport } from './routes/volunteer.operations'
import { Route as VolunteerNotificationsRouteImport } from './routes/volunteer.notifications'
import { Route as VolunteerMissionsRouteImport } from './routes/volunteer.missions'
import { Route as VolunteerIncidentsRouteImport } from './routes/volunteer.incidents'
import { Route as VolunteerActiveRouteImport } from './routes/volunteer.active'
import { Route as VolunteerAchievementsRouteImport } from './routes/volunteer.achievements'
import { Route as RescueVehiclesRouteImport } from './routes/rescue.vehicles'
import { Route as RescueResourcesRouteImport } from './routes/rescue.resources'
import { Route as RescueProfileRouteImport } from './routes/rescue.profile'
import { Route as RescuePersonnelRouteImport } from './routes/rescue.personnel'
import { Route as RescueOperationsRouteImport } from './routes/rescue.operations'
import { Route as RescueIncidentsRouteImport } from './routes/rescue.incidents'
import { Route as RescueDispatchRouteImport } from './routes/rescue.dispatch'
import { Route as RescueAnalyticsRouteImport } from './routes/rescue.analytics'
import { Route as CitizenSosRouteImport } from './routes/citizen.sos'
import { Route as CitizenSheltersRouteImport } from './routes/citizen.shelters'
import { Route as CitizenReportRouteImport } from './routes/citizen.report'
import { Route as CitizenProfileRouteImport } from './routes/citizen.profile'
import { Route as CitizenNotificationsRouteImport } from './routes/citizen.notifications'
import { Route as CitizenMedicalRouteImport } from './routes/citizen.medical'
import { Route as CitizenMapRouteImport } from './routes/citizen.map'
import { Route as CitizenIncidentsRouteImport } from './routes/citizen.incidents'
import { Route as CitizenHistoryRouteImport } from './routes/citizen.history'
import { Route as CitizenAssistantRouteImport } from './routes/citizen.assistant'
import { Route as AuthorityVolunteersRouteImport } from './routes/authority.volunteers'
import { Route as AuthorityTeamsRouteImport } from './routes/authority.teams'
import { Route as AuthoritySheltersRouteImport } from './routes/authority.shelters'
import { Route as AuthorityResourcesRouteImport } from './routes/authority.resources'
import { Route as AuthorityRequestsRouteImport } from './routes/authority.requests'
import { Route as AuthorityProfileRouteImport } from './routes/authority.profile'
import { Route as AuthorityMonitoringRouteImport } from './routes/authority.monitoring'
import { Route as AuthorityIncidentsRouteImport } from './routes/authority.incidents'
import { Route as AuthorityDispatchRouteImport } from './routes/authority.dispatch'
import { Route as AuthorityAnalyticsRouteImport } from './routes/authority.analytics'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as RescueIncidentsIdRouteImport } from './routes/rescue.incidents.$id'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const RescueRoute = RescueRouteImport.update({
  id: '/rescue',
  path: '/rescue',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityRoute = AuthorityRouteImport.update({
  id: '/authority',
  path: '/authority',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerIndexRoute = VolunteerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VolunteerRoute,
} as any)
const RescueIndexRoute = RescueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RescueRoute,
} as any)
const CitizenIndexRoute = CitizenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitizenRoute,
} as any)
const AuthorityIndexRoute = AuthorityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthorityRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VolunteerTrainingRoute = VolunteerTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => VolunteerRoute,
} as any)
const VolunteerResourcesRoute = VolunteerResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => VolunteerRoute,
} as any)
const VolunteerProfileRoute = VolunteerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => VolunteerRoute,
} as any)
const VolunteerOperationsRoute = VolunteerOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => VolunteerRoute,
} as any)
const VolunteerNotificationsRoute = VolunteerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => VolunteerRoute,
} as any)
const VolunteerMissionsRoute = VolunteerMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => VolunteerRoute,
} as any)
const VolunteerIncidentsRoute = VolunteerIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => VolunteerRoute,
} as any)
const VolunteerActiveRoute = VolunteerActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => VolunteerRoute,
} as any)
const VolunteerAchievementsRoute = VolunteerAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => VolunteerRoute,
} as any)
const RescueVehiclesRoute = RescueVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => RescueRoute,
} as any)
const RescueResourcesRoute = RescueResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => RescueRoute,
} as any)
const RescueProfileRoute = RescueProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => RescueRoute,
} as any)
const RescuePersonnelRoute = RescuePersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => RescueRoute,
} as any)
const RescueOperationsRoute = RescueOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => RescueRoute,
} as any)
const RescueIncidentsRoute = RescueIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => RescueRoute,
} as any)
const RescueDispatchRoute = RescueDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => RescueRoute,
} as any)
const RescueAnalyticsRoute = RescueAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => RescueRoute,
} as any)
const CitizenSosRoute = CitizenSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenSheltersRoute = CitizenSheltersRouteImport.update({
  id: '/shelters',
  path: '/shelters',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenReportRoute = CitizenReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenProfileRoute = CitizenProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenNotificationsRoute = CitizenNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenMedicalRoute = CitizenMedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenMapRoute = CitizenMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenIncidentsRoute = CitizenIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenHistoryRoute = CitizenHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenAssistantRoute = CitizenAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => CitizenRoute,
} as any)
const AuthorityVolunteersRoute = AuthorityVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityTeamsRoute = AuthorityTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthoritySheltersRoute = AuthoritySheltersRouteImport.update({
  id: '/shelters',
  path: '/shelters',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityResourcesRoute = AuthorityResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityRequestsRoute = AuthorityRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityProfileRoute = AuthorityProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityMonitoringRoute = AuthorityMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityIncidentsRoute = AuthorityIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityDispatchRoute = AuthorityDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityAnalyticsRoute = AuthorityAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthorityRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const RescueIncidentsIdRoute = RescueIncidentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RescueIncidentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/authority': typeof AuthorityRouteWithChildren
  '/citizen': typeof CitizenRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/rescue': typeof RescueRouteWithChildren
  '/volunteer': typeof VolunteerRouteWithChildren
  '/admin/health': typeof AdminHealthRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/authority/analytics': typeof AuthorityAnalyticsRoute
  '/authority/dispatch': typeof AuthorityDispatchRoute
  '/authority/incidents': typeof AuthorityIncidentsRoute
  '/authority/monitoring': typeof AuthorityMonitoringRoute
  '/authority/profile': typeof AuthorityProfileRoute
  '/authority/requests': typeof AuthorityRequestsRoute
  '/authority/resources': typeof AuthorityResourcesRoute
  '/authority/shelters': typeof AuthoritySheltersRoute
  '/authority/teams': typeof AuthorityTeamsRoute
  '/authority/volunteers': typeof AuthorityVolunteersRoute
  '/citizen/assistant': typeof CitizenAssistantRoute
  '/citizen/history': typeof CitizenHistoryRoute
  '/citizen/incidents': typeof CitizenIncidentsRoute
  '/citizen/map': typeof CitizenMapRoute
  '/citizen/medical': typeof CitizenMedicalRoute
  '/citizen/notifications': typeof CitizenNotificationsRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/report': typeof CitizenReportRoute
  '/citizen/shelters': typeof CitizenSheltersRoute
  '/citizen/sos': typeof CitizenSosRoute
  '/rescue/analytics': typeof RescueAnalyticsRoute
  '/rescue/dispatch': typeof RescueDispatchRoute
  '/rescue/incidents': typeof RescueIncidentsRouteWithChildren
  '/rescue/operations': typeof RescueOperationsRoute
  '/rescue/personnel': typeof RescuePersonnelRoute
  '/rescue/profile': typeof RescueProfileRoute
  '/rescue/resources': typeof RescueResourcesRoute
  '/rescue/vehicles': typeof RescueVehiclesRoute
  '/volunteer/achievements': typeof VolunteerAchievementsRoute
  '/volunteer/active': typeof VolunteerActiveRoute
  '/volunteer/incidents': typeof VolunteerIncidentsRoute
  '/volunteer/missions': typeof VolunteerMissionsRoute
  '/volunteer/notifications': typeof VolunteerNotificationsRoute
  '/volunteer/operations': typeof VolunteerOperationsRoute
  '/volunteer/profile': typeof VolunteerProfileRoute
  '/volunteer/resources': typeof VolunteerResourcesRoute
  '/volunteer/training': typeof VolunteerTrainingRoute
  '/admin/': typeof AdminIndexRoute
  '/authority/': typeof AuthorityIndexRoute
  '/citizen/': typeof CitizenIndexRoute
  '/rescue/': typeof RescueIndexRoute
  '/volunteer/': typeof VolunteerIndexRoute
  '/rescue/incidents/$id': typeof RescueIncidentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/authority/analytics': typeof AuthorityAnalyticsRoute
  '/authority/dispatch': typeof AuthorityDispatchRoute
  '/authority/incidents': typeof AuthorityIncidentsRoute
  '/authority/monitoring': typeof AuthorityMonitoringRoute
  '/authority/profile': typeof AuthorityProfileRoute
  '/authority/requests': typeof AuthorityRequestsRoute
  '/authority/resources': typeof AuthorityResourcesRoute
  '/authority/shelters': typeof AuthoritySheltersRoute
  '/authority/teams': typeof AuthorityTeamsRoute
  '/authority/volunteers': typeof AuthorityVolunteersRoute
  '/citizen/assistant': typeof CitizenAssistantRoute
  '/citizen/history': typeof CitizenHistoryRoute
  '/citizen/incidents': typeof CitizenIncidentsRoute
  '/citizen/map': typeof CitizenMapRoute
  '/citizen/medical': typeof CitizenMedicalRoute
  '/citizen/notifications': typeof CitizenNotificationsRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/report': typeof CitizenReportRoute
  '/citizen/shelters': typeof CitizenSheltersRoute
  '/citizen/sos': typeof CitizenSosRoute
  '/rescue/analytics': typeof RescueAnalyticsRoute
  '/rescue/dispatch': typeof RescueDispatchRoute
  '/rescue/incidents': typeof RescueIncidentsRouteWithChildren
  '/rescue/operations': typeof RescueOperationsRoute
  '/rescue/personnel': typeof RescuePersonnelRoute
  '/rescue/profile': typeof RescueProfileRoute
  '/rescue/resources': typeof RescueResourcesRoute
  '/rescue/vehicles': typeof RescueVehiclesRoute
  '/volunteer/achievements': typeof VolunteerAchievementsRoute
  '/volunteer/active': typeof VolunteerActiveRoute
  '/volunteer/incidents': typeof VolunteerIncidentsRoute
  '/volunteer/missions': typeof VolunteerMissionsRoute
  '/volunteer/notifications': typeof VolunteerNotificationsRoute
  '/volunteer/operations': typeof VolunteerOperationsRoute
  '/volunteer/profile': typeof VolunteerProfileRoute
  '/volunteer/resources': typeof VolunteerResourcesRoute
  '/volunteer/training': typeof VolunteerTrainingRoute
  '/admin': typeof AdminIndexRoute
  '/authority': typeof AuthorityIndexRoute
  '/citizen': typeof CitizenIndexRoute
  '/rescue': typeof RescueIndexRoute
  '/volunteer': typeof VolunteerIndexRoute
  '/rescue/incidents/$id': typeof RescueIncidentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/authority': typeof AuthorityRouteWithChildren
  '/citizen': typeof CitizenRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/rescue': typeof RescueRouteWithChildren
  '/volunteer': typeof VolunteerRouteWithChildren
  '/admin/health': typeof AdminHealthRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/authority/analytics': typeof AuthorityAnalyticsRoute
  '/authority/dispatch': typeof AuthorityDispatchRoute
  '/authority/incidents': typeof AuthorityIncidentsRoute
  '/authority/monitoring': typeof AuthorityMonitoringRoute
  '/authority/profile': typeof AuthorityProfileRoute
  '/authority/requests': typeof AuthorityRequestsRoute
  '/authority/resources': typeof AuthorityResourcesRoute
  '/authority/shelters': typeof AuthoritySheltersRoute
  '/authority/teams': typeof AuthorityTeamsRoute
  '/authority/volunteers': typeof AuthorityVolunteersRoute
  '/citizen/assistant': typeof CitizenAssistantRoute
  '/citizen/history': typeof CitizenHistoryRoute
  '/citizen/incidents': typeof CitizenIncidentsRoute
  '/citizen/map': typeof CitizenMapRoute
  '/citizen/medical': typeof CitizenMedicalRoute
  '/citizen/notifications': typeof CitizenNotificationsRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/report': typeof CitizenReportRoute
  '/citizen/shelters': typeof CitizenSheltersRoute
  '/citizen/sos': typeof CitizenSosRoute
  '/rescue/analytics': typeof RescueAnalyticsRoute
  '/rescue/dispatch': typeof RescueDispatchRoute
  '/rescue/incidents': typeof RescueIncidentsRouteWithChildren
  '/rescue/operations': typeof RescueOperationsRoute
  '/rescue/personnel': typeof RescuePersonnelRoute
  '/rescue/profile': typeof RescueProfileRoute
  '/rescue/resources': typeof RescueResourcesRoute
  '/rescue/vehicles': typeof RescueVehiclesRoute
  '/volunteer/achievements': typeof VolunteerAchievementsRoute
  '/volunteer/active': typeof VolunteerActiveRoute
  '/volunteer/incidents': typeof VolunteerIncidentsRoute
  '/volunteer/missions': typeof VolunteerMissionsRoute
  '/volunteer/notifications': typeof VolunteerNotificationsRoute
  '/volunteer/operations': typeof VolunteerOperationsRoute
  '/volunteer/profile': typeof VolunteerProfileRoute
  '/volunteer/resources': typeof VolunteerResourcesRoute
  '/volunteer/training': typeof VolunteerTrainingRoute
  '/admin/': typeof AdminIndexRoute
  '/authority/': typeof AuthorityIndexRoute
  '/citizen/': typeof CitizenIndexRoute
  '/rescue/': typeof RescueIndexRoute
  '/volunteer/': typeof VolunteerIndexRoute
  '/rescue/incidents/$id': typeof RescueIncidentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/authority'
    | '/citizen'
    | '/login'
    | '/register'
    | '/rescue'
    | '/volunteer'
    | '/admin/health'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/users'
    | '/authority/analytics'
    | '/authority/dispatch'
    | '/authority/incidents'
    | '/authority/monitoring'
    | '/authority/profile'
    | '/authority/requests'
    | '/authority/resources'
    | '/authority/shelters'
    | '/authority/teams'
    | '/authority/volunteers'
    | '/citizen/assistant'
    | '/citizen/history'
    | '/citizen/incidents'
    | '/citizen/map'
    | '/citizen/medical'
    | '/citizen/notifications'
    | '/citizen/profile'
    | '/citizen/report'
    | '/citizen/shelters'
    | '/citizen/sos'
    | '/rescue/analytics'
    | '/rescue/dispatch'
    | '/rescue/incidents'
    | '/rescue/operations'
    | '/rescue/personnel'
    | '/rescue/profile'
    | '/rescue/resources'
    | '/rescue/vehicles'
    | '/volunteer/achievements'
    | '/volunteer/active'
    | '/volunteer/incidents'
    | '/volunteer/missions'
    | '/volunteer/notifications'
    | '/volunteer/operations'
    | '/volunteer/profile'
    | '/volunteer/resources'
    | '/volunteer/training'
    | '/admin/'
    | '/authority/'
    | '/citizen/'
    | '/rescue/'
    | '/volunteer/'
    | '/rescue/incidents/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/health'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/users'
    | '/authority/analytics'
    | '/authority/dispatch'
    | '/authority/incidents'
    | '/authority/monitoring'
    | '/authority/profile'
    | '/authority/requests'
    | '/authority/resources'
    | '/authority/shelters'
    | '/authority/teams'
    | '/authority/volunteers'
    | '/citizen/assistant'
    | '/citizen/history'
    | '/citizen/incidents'
    | '/citizen/map'
    | '/citizen/medical'
    | '/citizen/notifications'
    | '/citizen/profile'
    | '/citizen/report'
    | '/citizen/shelters'
    | '/citizen/sos'
    | '/rescue/analytics'
    | '/rescue/dispatch'
    | '/rescue/incidents'
    | '/rescue/operations'
    | '/rescue/personnel'
    | '/rescue/profile'
    | '/rescue/resources'
    | '/rescue/vehicles'
    | '/volunteer/achievements'
    | '/volunteer/active'
    | '/volunteer/incidents'
    | '/volunteer/missions'
    | '/volunteer/notifications'
    | '/volunteer/operations'
    | '/volunteer/profile'
    | '/volunteer/resources'
    | '/volunteer/training'
    | '/admin'
    | '/authority'
    | '/citizen'
    | '/rescue'
    | '/volunteer'
    | '/rescue/incidents/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/authority'
    | '/citizen'
    | '/login'
    | '/register'
    | '/rescue'
    | '/volunteer'
    | '/admin/health'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/users'
    | '/authority/analytics'
    | '/authority/dispatch'
    | '/authority/incidents'
    | '/authority/monitoring'
    | '/authority/profile'
    | '/authority/requests'
    | '/authority/resources'
    | '/authority/shelters'
    | '/authority/teams'
    | '/authority/volunteers'
    | '/citizen/assistant'
    | '/citizen/history'
    | '/citizen/incidents'
    | '/citizen/map'
    | '/citizen/medical'
    | '/citizen/notifications'
    | '/citizen/profile'
    | '/citizen/report'
    | '/citizen/shelters'
    | '/citizen/sos'
    | '/rescue/analytics'
    | '/rescue/dispatch'
    | '/rescue/incidents'
    | '/rescue/operations'
    | '/rescue/personnel'
    | '/rescue/profile'
    | '/rescue/resources'
    | '/rescue/vehicles'
    | '/volunteer/achievements'
    | '/volunteer/active'
    | '/volunteer/incidents'
    | '/volunteer/missions'
    | '/volunteer/notifications'
    | '/volunteer/operations'
    | '/volunteer/profile'
    | '/volunteer/resources'
    | '/volunteer/training'
    | '/admin/'
    | '/authority/'
    | '/citizen/'
    | '/rescue/'
    | '/volunteer/'
    | '/rescue/incidents/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthorityRoute: typeof AuthorityRouteWithChildren
  CitizenRoute: typeof CitizenRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RescueRoute: typeof RescueRouteWithChildren
  VolunteerRoute: typeof VolunteerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rescue': {
      id: '/rescue'
      path: '/rescue'
      fullPath: '/rescue'
      preLoaderRoute: typeof RescueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority': {
      id: '/authority'
      path: '/authority'
      fullPath: '/authority'
      preLoaderRoute: typeof AuthorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/': {
      id: '/volunteer/'
      path: '/'
      fullPath: '/volunteer/'
      preLoaderRoute: typeof VolunteerIndexRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/rescue/': {
      id: '/rescue/'
      path: '/'
      fullPath: '/rescue/'
      preLoaderRoute: typeof RescueIndexRouteImport
      parentRoute: typeof RescueRoute
    }
    '/citizen/': {
      id: '/citizen/'
      path: '/'
      fullPath: '/citizen/'
      preLoaderRoute: typeof CitizenIndexRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/authority/': {
      id: '/authority/'
      path: '/'
      fullPath: '/authority/'
      preLoaderRoute: typeof AuthorityIndexRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/volunteer/training': {
      id: '/volunteer/training'
      path: '/training'
      fullPath: '/volunteer/training'
      preLoaderRoute: typeof VolunteerTrainingRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/volunteer/resources': {
      id: '/volunteer/resources'
      path: '/resources'
      fullPath: '/volunteer/resources'
      preLoaderRoute: typeof VolunteerResourcesRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/volunteer/profile': {
      id: '/volunteer/profile'
      path: '/profile'
      fullPath: '/volunteer/profile'
      preLoaderRoute: typeof VolunteerProfileRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/volunteer/operations': {
      id: '/volunteer/operations'
      path: '/operations'
      fullPath: '/volunteer/operations'
      preLoaderRoute: typeof VolunteerOperationsRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/volunteer/notifications': {
      id: '/volunteer/notifications'
      path: '/notifications'
      fullPath: '/volunteer/notifications'
      preLoaderRoute: typeof VolunteerNotificationsRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/volunteer/missions': {
      id: '/volunteer/missions'
      path: '/missions'
      fullPath: '/volunteer/missions'
      preLoaderRoute: typeof VolunteerMissionsRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/volunteer/incidents': {
      id: '/volunteer/incidents'
      path: '/incidents'
      fullPath: '/volunteer/incidents'
      preLoaderRoute: typeof VolunteerIncidentsRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/volunteer/active': {
      id: '/volunteer/active'
      path: '/active'
      fullPath: '/volunteer/active'
      preLoaderRoute: typeof VolunteerActiveRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/volunteer/achievements': {
      id: '/volunteer/achievements'
      path: '/achievements'
      fullPath: '/volunteer/achievements'
      preLoaderRoute: typeof VolunteerAchievementsRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/rescue/vehicles': {
      id: '/rescue/vehicles'
      path: '/vehicles'
      fullPath: '/rescue/vehicles'
      preLoaderRoute: typeof RescueVehiclesRouteImport
      parentRoute: typeof RescueRoute
    }
    '/rescue/resources': {
      id: '/rescue/resources'
      path: '/resources'
      fullPath: '/rescue/resources'
      preLoaderRoute: typeof RescueResourcesRouteImport
      parentRoute: typeof RescueRoute
    }
    '/rescue/profile': {
      id: '/rescue/profile'
      path: '/profile'
      fullPath: '/rescue/profile'
      preLoaderRoute: typeof RescueProfileRouteImport
      parentRoute: typeof RescueRoute
    }
    '/rescue/personnel': {
      id: '/rescue/personnel'
      path: '/personnel'
      fullPath: '/rescue/personnel'
      preLoaderRoute: typeof RescuePersonnelRouteImport
      parentRoute: typeof RescueRoute
    }
    '/rescue/operations': {
      id: '/rescue/operations'
      path: '/operations'
      fullPath: '/rescue/operations'
      preLoaderRoute: typeof RescueOperationsRouteImport
      parentRoute: typeof RescueRoute
    }
    '/rescue/incidents': {
      id: '/rescue/incidents'
      path: '/incidents'
      fullPath: '/rescue/incidents'
      preLoaderRoute: typeof RescueIncidentsRouteImport
      parentRoute: typeof RescueRoute
    }
    '/rescue/dispatch': {
      id: '/rescue/dispatch'
      path: '/dispatch'
      fullPath: '/rescue/dispatch'
      preLoaderRoute: typeof RescueDispatchRouteImport
      parentRoute: typeof RescueRoute
    }
    '/rescue/analytics': {
      id: '/rescue/analytics'
      path: '/analytics'
      fullPath: '/rescue/analytics'
      preLoaderRoute: typeof RescueAnalyticsRouteImport
      parentRoute: typeof RescueRoute
    }
    '/citizen/sos': {
      id: '/citizen/sos'
      path: '/sos'
      fullPath: '/citizen/sos'
      preLoaderRoute: typeof CitizenSosRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/shelters': {
      id: '/citizen/shelters'
      path: '/shelters'
      fullPath: '/citizen/shelters'
      preLoaderRoute: typeof CitizenSheltersRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/report': {
      id: '/citizen/report'
      path: '/report'
      fullPath: '/citizen/report'
      preLoaderRoute: typeof CitizenReportRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/profile': {
      id: '/citizen/profile'
      path: '/profile'
      fullPath: '/citizen/profile'
      preLoaderRoute: typeof CitizenProfileRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/notifications': {
      id: '/citizen/notifications'
      path: '/notifications'
      fullPath: '/citizen/notifications'
      preLoaderRoute: typeof CitizenNotificationsRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/medical': {
      id: '/citizen/medical'
      path: '/medical'
      fullPath: '/citizen/medical'
      preLoaderRoute: typeof CitizenMedicalRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/map': {
      id: '/citizen/map'
      path: '/map'
      fullPath: '/citizen/map'
      preLoaderRoute: typeof CitizenMapRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/incidents': {
      id: '/citizen/incidents'
      path: '/incidents'
      fullPath: '/citizen/incidents'
      preLoaderRoute: typeof CitizenIncidentsRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/history': {
      id: '/citizen/history'
      path: '/history'
      fullPath: '/citizen/history'
      preLoaderRoute: typeof CitizenHistoryRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/assistant': {
      id: '/citizen/assistant'
      path: '/assistant'
      fullPath: '/citizen/assistant'
      preLoaderRoute: typeof CitizenAssistantRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/authority/volunteers': {
      id: '/authority/volunteers'
      path: '/volunteers'
      fullPath: '/authority/volunteers'
      preLoaderRoute: typeof AuthorityVolunteersRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/teams': {
      id: '/authority/teams'
      path: '/teams'
      fullPath: '/authority/teams'
      preLoaderRoute: typeof AuthorityTeamsRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/shelters': {
      id: '/authority/shelters'
      path: '/shelters'
      fullPath: '/authority/shelters'
      preLoaderRoute: typeof AuthoritySheltersRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/resources': {
      id: '/authority/resources'
      path: '/resources'
      fullPath: '/authority/resources'
      preLoaderRoute: typeof AuthorityResourcesRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/requests': {
      id: '/authority/requests'
      path: '/requests'
      fullPath: '/authority/requests'
      preLoaderRoute: typeof AuthorityRequestsRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/profile': {
      id: '/authority/profile'
      path: '/profile'
      fullPath: '/authority/profile'
      preLoaderRoute: typeof AuthorityProfileRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/monitoring': {
      id: '/authority/monitoring'
      path: '/monitoring'
      fullPath: '/authority/monitoring'
      preLoaderRoute: typeof AuthorityMonitoringRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/incidents': {
      id: '/authority/incidents'
      path: '/incidents'
      fullPath: '/authority/incidents'
      preLoaderRoute: typeof AuthorityIncidentsRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/dispatch': {
      id: '/authority/dispatch'
      path: '/dispatch'
      fullPath: '/authority/dispatch'
      preLoaderRoute: typeof AuthorityDispatchRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/analytics': {
      id: '/authority/analytics'
      path: '/analytics'
      fullPath: '/authority/analytics'
      preLoaderRoute: typeof AuthorityAnalyticsRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/rescue/incidents/$id': {
      id: '/rescue/incidents/$id'
      path: '/$id'
      fullPath: '/rescue/incidents/$id'
      preLoaderRoute: typeof RescueIncidentsIdRouteImport
      parentRoute: typeof RescueIncidentsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminHealthRoute: typeof AdminHealthRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminHealthRoute: AdminHealthRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthorityRouteChildren {
  AuthorityAnalyticsRoute: typeof AuthorityAnalyticsRoute
  AuthorityDispatchRoute: typeof AuthorityDispatchRoute
  AuthorityIncidentsRoute: typeof AuthorityIncidentsRoute
  AuthorityMonitoringRoute: typeof AuthorityMonitoringRoute
  AuthorityProfileRoute: typeof AuthorityProfileRoute
  AuthorityRequestsRoute: typeof AuthorityRequestsRoute
  AuthorityResourcesRoute: typeof AuthorityResourcesRoute
  AuthoritySheltersRoute: typeof AuthoritySheltersRoute
  AuthorityTeamsRoute: typeof AuthorityTeamsRoute
  AuthorityVolunteersRoute: typeof AuthorityVolunteersRoute
  AuthorityIndexRoute: typeof AuthorityIndexRoute
}

const AuthorityRouteChildren: AuthorityRouteChildren = {
  AuthorityAnalyticsRoute: AuthorityAnalyticsRoute,
  AuthorityDispatchRoute: AuthorityDispatchRoute,
  AuthorityIncidentsRoute: AuthorityIncidentsRoute,
  AuthorityMonitoringRoute: AuthorityMonitoringRoute,
  AuthorityProfileRoute: AuthorityProfileRoute,
  AuthorityRequestsRoute: AuthorityRequestsRoute,
  AuthorityResourcesRoute: AuthorityResourcesRoute,
  AuthoritySheltersRoute: AuthoritySheltersRoute,
  AuthorityTeamsRoute: AuthorityTeamsRoute,
  AuthorityVolunteersRoute: AuthorityVolunteersRoute,
  AuthorityIndexRoute: AuthorityIndexRoute,
}

const AuthorityRouteWithChildren = AuthorityRoute._addFileChildren(
  AuthorityRouteChildren,
)

interface CitizenRouteChildren {
  CitizenAssistantRoute: typeof CitizenAssistantRoute
  CitizenHistoryRoute: typeof CitizenHistoryRoute
  CitizenIncidentsRoute: typeof CitizenIncidentsRoute
  CitizenMapRoute: typeof CitizenMapRoute
  CitizenMedicalRoute: typeof CitizenMedicalRoute
  CitizenNotificationsRoute: typeof CitizenNotificationsRoute
  CitizenProfileRoute: typeof CitizenProfileRoute
  CitizenReportRoute: typeof CitizenReportRoute
  CitizenSheltersRoute: typeof CitizenSheltersRoute
  CitizenSosRoute: typeof CitizenSosRoute
  CitizenIndexRoute: typeof CitizenIndexRoute
}

const CitizenRouteChildren: CitizenRouteChildren = {
  CitizenAssistantRoute: CitizenAssistantRoute,
  CitizenHistoryRoute: CitizenHistoryRoute,
  CitizenIncidentsRoute: CitizenIncidentsRoute,
  CitizenMapRoute: CitizenMapRoute,
  CitizenMedicalRoute: CitizenMedicalRoute,
  CitizenNotificationsRoute: CitizenNotificationsRoute,
  CitizenProfileRoute: CitizenProfileRoute,
  CitizenReportRoute: CitizenReportRoute,
  CitizenSheltersRoute: CitizenSheltersRoute,
  CitizenSosRoute: CitizenSosRoute,
  CitizenIndexRoute: CitizenIndexRoute,
}

const CitizenRouteWithChildren =
  CitizenRoute._addFileChildren(CitizenRouteChildren)

interface RescueIncidentsRouteChildren {
  RescueIncidentsIdRoute: typeof RescueIncidentsIdRoute
}

const RescueIncidentsRouteChildren: RescueIncidentsRouteChildren = {
  RescueIncidentsIdRoute: RescueIncidentsIdRoute,
}

const RescueIncidentsRouteWithChildren = RescueIncidentsRoute._addFileChildren(
  RescueIncidentsRouteChildren,
)

interface RescueRouteChildren {
  RescueAnalyticsRoute: typeof RescueAnalyticsRoute
  RescueDispatchRoute: typeof RescueDispatchRoute
  RescueIncidentsRoute: typeof RescueIncidentsRouteWithChildren
  RescueOperationsRoute: typeof RescueOperationsRoute
  RescuePersonnelRoute: typeof RescuePersonnelRoute
  RescueProfileRoute: typeof RescueProfileRoute
  RescueResourcesRoute: typeof RescueResourcesRoute
  RescueVehiclesRoute: typeof RescueVehiclesRoute
  RescueIndexRoute: typeof RescueIndexRoute
}

const RescueRouteChildren: RescueRouteChildren = {
  RescueAnalyticsRoute: RescueAnalyticsRoute,
  RescueDispatchRoute: RescueDispatchRoute,
  RescueIncidentsRoute: RescueIncidentsRouteWithChildren,
  RescueOperationsRoute: RescueOperationsRoute,
  RescuePersonnelRoute: RescuePersonnelRoute,
  RescueProfileRoute: RescueProfileRoute,
  RescueResourcesRoute: RescueResourcesRoute,
  RescueVehiclesRoute: RescueVehiclesRoute,
  RescueIndexRoute: RescueIndexRoute,
}

const RescueRouteWithChildren =
  RescueRoute._addFileChildren(RescueRouteChildren)

interface VolunteerRouteChildren {
  VolunteerAchievementsRoute: typeof VolunteerAchievementsRoute
  VolunteerActiveRoute: typeof VolunteerActiveRoute
  VolunteerIncidentsRoute: typeof VolunteerIncidentsRoute
  VolunteerMissionsRoute: typeof VolunteerMissionsRoute
  VolunteerNotificationsRoute: typeof VolunteerNotificationsRoute
  VolunteerOperationsRoute: typeof VolunteerOperationsRoute
  VolunteerProfileRoute: typeof VolunteerProfileRoute
  VolunteerResourcesRoute: typeof VolunteerResourcesRoute
  VolunteerTrainingRoute: typeof VolunteerTrainingRoute
  VolunteerIndexRoute: typeof VolunteerIndexRoute
}

const VolunteerRouteChildren: VolunteerRouteChildren = {
  VolunteerAchievementsRoute: VolunteerAchievementsRoute,
  VolunteerActiveRoute: VolunteerActiveRoute,
  VolunteerIncidentsRoute: VolunteerIncidentsRoute,
  VolunteerMissionsRoute: VolunteerMissionsRoute,
  VolunteerNotificationsRoute: VolunteerNotificationsRoute,
  VolunteerOperationsRoute: VolunteerOperationsRoute,
  VolunteerProfileRoute: VolunteerProfileRoute,
  VolunteerResourcesRoute: VolunteerResourcesRoute,
  VolunteerTrainingRoute: VolunteerTrainingRoute,
  VolunteerIndexRoute: VolunteerIndexRoute,
}

const VolunteerRouteWithChildren = VolunteerRoute._addFileChildren(
  VolunteerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthorityRoute: AuthorityRouteWithChildren,
  CitizenRoute: CitizenRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RescueRoute: RescueRouteWithChildren,
  VolunteerRoute: VolunteerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
